[package]
name = "netbox-label"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12", features=["json","blocking"]}
serde = { version = "1", features = ["derive"] }
nusb = "0.1"
futures-lite = "2"
rand = "0.9.0"